// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1qbPYrSM6VesE7xcN9NLM7_O5OKxEvU8',
    appId: '1:969846984723:web:5c9e50fea13d3480d8efe6',
    messagingSenderId: '969846984723',
    projectId: 'rent-finder-app-2a279',
    authDomain: 'rent-finder-app-2a279.firebaseapp.com',
    storageBucket: 'rent-finder-app-2a279.firebasestorage.app',
    measurementId: 'G-J3QHYB49X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCip5Gr6BhcO_DsDz3ZX4v4WfZWbdydsyY',
    appId: '1:969846984723:android:f94b8b2b3c200049d8efe6',
    messagingSenderId: '969846984723',
    projectId: 'rent-finder-app-2a279',
    storageBucket: 'rent-finder-app-2a279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ghztEMo5NetZ8uTUDfP1IaI2F7PG5r8',
    appId: '1:969846984723:ios:3ea3f470ca721076d8efe6',
    messagingSenderId: '969846984723',
    projectId: 'rent-finder-app-2a279',
    storageBucket: 'rent-finder-app-2a279.firebasestorage.app',
    iosBundleId: 'com.example.rentfinderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ghztEMo5NetZ8uTUDfP1IaI2F7PG5r8',
    appId: '1:969846984723:ios:3ea3f470ca721076d8efe6',
    messagingSenderId: '969846984723',
    projectId: 'rent-finder-app-2a279',
    storageBucket: 'rent-finder-app-2a279.firebasestorage.app',
    iosBundleId: 'com.example.rentfinderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1qbPYrSM6VesE7xcN9NLM7_O5OKxEvU8',
    appId: '1:969846984723:web:7d9bb02708d016f2d8efe6',
    messagingSenderId: '969846984723',
    projectId: 'rent-finder-app-2a279',
    authDomain: 'rent-finder-app-2a279.firebaseapp.com',
    storageBucket: 'rent-finder-app-2a279.firebasestorage.app',
    measurementId: 'G-CW2DXKMXB8',
  );
}
